packages:
  - "../packages/ai"
  - "../packages/customer-portal"
  - "../packages/dev-engine"
  - "../packages/ember-core"
  - "../packages/ember-ui"
  - "../packages/fleetops"
  - "../packages/fleetops-data"
  - "../packages/iam-engine"
  - "../packages/ledger"
  - "../packages/registry-bridge"
  - "../packages/storefront"
linkWorkspacePackages: deep
preferWorkspacePackages: true
publicHoistPattern:
  - "*ember-core*"
  - "*ember-ui*"
  - "*fleetops-data*"
overrides:
  "@fleetbase/fleetops-data": "workspace:*"
  "@fleetbase/ember-core": "workspace:*"
  "@fleetbase/ember-ui": "workspace:*"
allowBuilds:
  "@fortawesome/fontawesome-common-types": false
  "@fortawesome/fontawesome-svg-core": false
  "@fortawesome/free-brands-svg-icons": false
  "@fortawesome/free-solid-svg-icons": false
  core-js: false
  fsevents: false
minimumReleaseAgeExclude:
  - "@fleetbase/ember-ui@0.4.0"
  - "@fleetbase/fleetops-data@0.2.0"
  - "@fleetbase/fleetops-engine@0.6.65"
